[CI]
color = "008672"
name = "CI"
description = "CI/CD"

[breaking-change]
color = "d73a4a"
name = "breaking-change"
description = "Breaking changes"

[bug]
color = "d73a4a"
name = "bug"
description = "Something isn't working"

[chore]
color = "d73a4a"
name = "chore"
description = "Chore changes"

[dependencies]
color = "0366d6"
name = "dependencies"
description = "Dependencies"

[docs]
color = "7057ff"
name = "docs"
description = "Documents"

[duplicate]
color = "cfd3d7"
name = "duplicate"
description = "This issue or pull request already exists"

[enhancement]
color = "27C1FD"
name = "enhancement"
description = "Enhancement"

[feature]
color = "27C1FD"
name = "feature"
description = "New Features"

[fix]
color = "d73a4a"
name = "fix"
description = "Bug fix"

[invalid]
color = "e4e669"
name = "invalid"
description = "This will not be worked on"

[performance]
color = "d73a4a"
name = "performance"
description = "Performance improvements"

[refactor]
color = "27C1FD"
name = "refactor"
description = "Refactoring"

[test]
color = "a2eeef"
name = "test"
description = "Add test"

[wontfix]
color = "ffffff"
name = "wontfix"
description = "This will not be worked on"
