changelog:
  exclude:
    labels:
      - 'ignore-for-changelog'
    authors:
      - octocat
  categories:
    - title: '❗ Breaking Changes'  
      labels:
        - breaking-change
    - title: '🚀 Features'
      labels:
        - 'feature'
        - 'enhancement'
    - title: '🐛 Bug Fixes'
      labels:
        - 'fix'
        - 'bugfix'
        - 'bug'
    - title: '⚡ Performance improvements'
      labels:
        - 'performance'
    - title: '🧰 Maintenance'
      labels:
        - 'chore'
        - 'refactor'
    - title: '🏭 Tests'
      labels:
        - 'tests'
    - title: '📖 Docs'
      labels:
        - 'docs'
    - title: '🛠 Examples'
      labels:
        - 'examples'
    - title: '🧰 Misc'
      labels:
        - 'build'
        - 'meta'
        - 'chore'
        - 'CI'
    - title: '📦 Dependencies'
      labels:
        - 'dependencies'
